In [2]:
import numpy as np

In [ ]:
Basic array creation

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
a = [1,2,3.5,4,]
a

[1, 2, 3.5, 4]

In [8]:
np.array(a)

array([1. , 2. , 3.5, 4. ])

In [9]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
Array Genration function

In [13]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [16]:
arr = np.zeros((6,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
arr = np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
arr = np.linspace(0,1,50)
arr

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [ ]:
Random Genration function

In [22]:
arr = np.random.rand(10)
arr

array([0.05401272, 0.94810849, 0.9912915 , 0.32381687, 0.21028547,
       0.72577376, 0.75382842, 0.25075452, 0.70461354, 0.81585134])

In [24]:
arr = np.random.randn(10)
arr

array([-2.18224772,  0.51291281, -0.14753588,  1.60985941, -1.19698547,
       -0.73316311, -1.54679333,  2.45974685,  0.11842384, -0.60771553])

In [27]:
arr = np.random.randint(10,20,10)
arr

array([15, 14, 19, 12, 14, 10, 11, 10, 17, 19], dtype=int32)

In [ ]:
Array Attribute

In [28]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr.shape

(3, 3)

In [30]:
arr.size

9

In [31]:
arr.dtype

dtype('int64')

In [ ]:
Array Methods

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr.min()

np.int64(1)

In [34]:
arr.max()

np.int64(9)

In [35]:
arr.sum()

np.int64(45)

In [38]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [39]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [40]:
arr.mean()

np.float64(5.0)

In [41]:
arr.std()

np.float64(2.581988897471611)

In [42]:
arr.argmax()

np.int64(8)

In [43]:
arr.argmin()

np.int64(0)

In [ ]:
Reshaping and Resizing

In [44]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [46]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [47]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])