In [ ]:
import numpy as np

In [ ]:
ARRAY OPERATION
Arithmetic operations

In [11]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [13]:
arr_sum = a1 + a2
arr_sum

array([ 7,  9, 11, 13, 15])

In [14]:
arr_sub = a1 - a2
arr_sub

array([-5, -5, -5, -5, -5])

In [15]:
arr_multi = a1 * a2
arr_multi

array([ 6, 14, 24, 36, 50])

In [16]:
arr_div = a1 /a2
arr_div

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [17]:
arra_div = a1 // a2
arra_div

array([0, 0, 0, 0, 0])

In [18]:
pow = a1 ** a2
pow

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
BROADCASTING

In [25]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [21]:
arr + 10

array([20, 30, 40, 50])

In [22]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [ ]:
DEEP AND SHALLOW COPY

In [34]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [36]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
a
b = a.copy()
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
MATRIX OPERATION

In [40]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [41]:
A

array([[1, 2],
       [3, 4]])

In [42]:
B

array([[5, 6],
       [7, 8]])

In [43]:
A @ B

array([[19, 22],
       [43, 50]])

In [44]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [45]:
A.T

array([[1, 3],
       [2, 4]])

In [46]:
B.T

array([[5, 7],
       [6, 8]])

In [ ]:
Advance Array Manipulation

In [ ]:
Stacking Array

In [50]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [51]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
SPLITTING ARRAY

In [54]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [57]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [56]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [60]:
a = np.vsplit(c,4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [61]:
for i in a :
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
