In [ ]:
Valid Sudoku

In [1]:
import numpy as np

In [2]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [3]:
s.sum()

np.int64(405)

In [4]:
np.sum(s,axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [6]:
b = np.sum(s,axis=1)
b == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [9]:
b = np.sum(s,axis=1)
for i in b:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("for rows it is valid")

for rows it is valid


In [8]:
c = np.sum(s,axis=0)
for i in c:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("for column it is valid")

for column it is valid


In [11]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [12]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [14]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [16]:
s[3:6,0:3]

array([[8, 5, 9],
       [4, 2, 6],
       [7, 1, 3]])

In [17]:
s[3:6,3:6]

array([[7, 6, 1],
       [8, 5, 3],
       [9, 2, 4]])

In [18]:
s[3:6,6:9]

array([[4, 2, 3],
       [7, 9, 1],
       [8, 5, 6]])

In [19]:
s[6:9,0:3]

array([[9, 6, 1],
       [2, 8, 7],
       [3, 4, 5]])

In [20]:
s[6:9,3:6]

array([[5, 3, 7],
       [4, 1, 9],
       [2, 8, 6]])

In [21]:
s[6:9,6:9]

array([[2, 8, 4],
       [6, 3, 5],
       [1, 7, 9]])

In [24]:
for i in range(0,9,3):
    for j in range(0,9,3):
       # print(s[i:i+3,j:j+3])
        n = s[i:i+3,j:j+3]
        print(n.sum())
    

45
45
45
45
45
45
45
45
45


In [23]:
n = s[i:i+3,j:j+3]
n.sum()

np.int64(45)

In [ ]:
General Questions

In [90]:
import numpy as numpy

# column : [Age, Math Marks, Science Marks]
data = np.array([
    [18,85,78], #Student 1
    [19,92,88], #Student 2
    [17,76,95], #Student 3
    [18,65,70], #Student 4
    [20,90,85] #Student 5
])

In [91]:
#get the shape of the matrix
data.shape

(5, 3)

In [92]:
#find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [93]:
#extract math marks of all student
data[:,1]

array([85, 92, 76, 65, 90])

In [94]:
#find the highest science marks.
np.max(data[:,2])

np.int64(95)

In [95]:
# get details of the student who scored more than 90 in math
data[:,1]>90

array([False,  True, False, False, False])

In [96]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [97]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [98]:
# increase math marks of all students by 5
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [99]:
# find how many student are younger than 19.
k = data[data[:,0]<19]
k



array([[18, 90, 78],
       [17, 81, 95],
       [18, 70, 70]])

In [100]:
len(data[data[:,0]<19])

3

In [101]:
# Calculate the average marks in each subject (column-wise mean)
data[:,1:]

array([[90, 78],
       [97, 88],
       [81, 95],
       [70, 70],
       [95, 85]])

In [102]:
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [103]:
# get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [104]:
# replace all science marks < 75 with 0
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])